#version: '8' # 과거 버전 호환성을 위해 주석 처리
services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbangbbang-game-server
    ports:
      - "8080:3000" # Dockerfile에서 EXPOSE한 포트와 맞춥니다.
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bbang-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  
